# Generated by Django 5.0.14 on 2026-01-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_cms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificateItem',
        ),
        migrations.DeleteModel(
            name='ContentBlock',
        ),
        migrations.DeleteModel(
            name='ProjectItem',
        ),
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Служебные данные формы', verbose_name='Доп. данные (JSON)'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='locale',
            field=models.CharField(default='ru', help_text='Например: ru или en', max_length=8, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
